CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE TABLE "Carts" (
        "CartId" text NOT NULL,
        "UserId" text NOT NULL,
        "ProductId" text NOT NULL,
        "Name" text NOT NULL,
        "ImageUrl" text NOT NULL,
        "Price" numeric NOT NULL,
        "Quantity" integer NOT NULL,
        "Size" text NOT NULL,
        CONSTRAINT "PK_Carts" PRIMARY KEY ("CartId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "OrderId" text NOT NULL,
        "UserId" text NOT NULL,
        "Username" text NOT NULL,
        "Date" text NOT NULL,
        "PaymentMethod" text NOT NULL,
        "ShippingAddress" text NOT NULL,
        "Status" text NOT NULL,
        "TotalAmount" numeric NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE TABLE "Products" (
        "ProductId" text NOT NULL,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "Category" text NOT NULL,
        "ImageUrl" text NOT NULL,
        "Price" numeric NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("ProductId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE TABLE "Users" (
        "UserId" text NOT NULL,
        "Username" text NOT NULL,
        "Address" text NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE TABLE "OrderProducts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" text NOT NULL,
        "CartId" text NOT NULL,
        "ProductId" text NOT NULL,
        "Name" text NOT NULL,
        "Image" text NOT NULL,
        "Quantity" integer NOT NULL,
        "Size" text NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "TotalPrice" numeric NOT NULL,
        CONSTRAINT "PK_OrderProducts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderProducts_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE TABLE "StockItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" text NOT NULL,
        "Size" text NOT NULL,
        "StockAmount" integer NOT NULL,
        CONSTRAINT "PK_StockItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StockItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE INDEX "IX_OrderProducts_OrderId" ON "OrderProducts" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    CREATE INDEX "IX_StockItems_ProductId" ON "StockItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260620223510_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260620223510_InitialCreate', '10.0.9');
    END IF;
END $EF$;
COMMIT;

